AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Parameters:
    BucketName:
      Description: Bucket Name
      Type: String
      ConstraintDescription: must be the name of an existing EC2 KeyPair.
Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: 
                Ref: BucketName # use your own unique name
            AccessControl: Private
          