Parameters:
    DBNameP:
        Type: String
        MinLength: "1"
        MaxLength: "64"
        AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MUser:
        Type: String
        MinLength: "1"
        MaxLength: "16"
        AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MPass:
        Type: String
        MinLength: "8"
        MaxLength: "41"
        AllowedPattern: "[a-zA-Z0-9]*"
        Description: "It shouldn't be less than 8 characters"
    
Resources:
    MyDBvideoInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            DBName: !Ref DBNameP
            MasterUsername: !Ref MUser
            MasterUserPassword: !Ref MPass
            Engine: MySQL
            EngineVersion: 8.0.19
            DBInstanceClass: db.t2.micro
            StorageType: gp2
            PubliclyAccessible: True
            AllocatedStorage: "20"
            DBInstanceIdentifier: !Join ["-",["MyDbInstance",!Ref "AWS::Region"]]
            AvailabilityZone: "us-east-1a"
        